# Generated by Django 4.0.4 on 2022-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_status',
            field=models.BooleanField(verbose_name='Тип'),
        ),
    ]
