# Generated by Django 4.0.4 on 2022-05-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='products.category'),
        ),
    ]
